#!/bin/sh
log=/tmp/queue_stat.log
> /tmp/queue_status.log
ll="`tail -1 /tmp/queue_status.log`"
n=1
while [ \( $n -le 3 \) -a \( -z "$ll" \) ];do
	sleep 1
        ll="`tail -1 /tmp/queue_status.log`"
	n=$((n + 1))
done
if [ $n -gt 3 ];then  
	msg="0 queue_stat queue=0|total_wrk=0|cur_wrk=0 queue=0 total_wrk=0 cur_wrk=0";
else
	msg="`echo "$ll"| awk '/workers a/{n=split($2,nn,"+");printf("0 queue_stat queue=%d|total_wrk=%d|cur_wrk=%d queue=%d total_wrk=%d cur_wrk=%d\n", $1, n, $13,$1, n, $13);}'`"
fi
echo $msg
echo $msg > $log

